<!DOCTYPE html>
<html lang="cs-cz">

<head>
	<base href="/localhost" />
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
	<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.1/dist/jquery.slim.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
	<title><?= $titulek ?></title>
	<meta name="description" content="<?= $popis ?>" />
	<meta name="keywords" content="<?= $klicova_slova ?>" />
	<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>
	<header>
		<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
			<!-- Brand/logo -->
			<a class="navbar-brand">PojištěníApp</a>
			<!-- Links -->
			<ul class="navbar-nav ml-5">
				<li class="nav-item">
					<a class="nav-link active" href="pojistenci">Pojištěnci</a>
				</li>
				<li class="nav-item">
					<a class="nav-link disabled">O aplikaci</a>
				</li>
			</ul>
		</nav>
	</header>

	<article>
		<?php $this->kontroler->vypisPohled(); // vložení aktuálního pohledu do šablony 
		?>
	</article>

</body>

</html>